### ISSUE TITLE
Dosen't work

### ISSUE THREAD

**Issue by alverman** [darknessii/rpi-matrix-artnet#2]
the pixels are not correctly addressed

**Comment by som3oneMw** [comment]
hey @alverman, did you ever get this working? I'm having trouble even getting anything to display. I'm sending data out of TouchDesigner and it's being received on the Pi, but I keep getting the following error:
`Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/udp.py", line 249, in doRead
    self.protocol.datagramReceived(data, addr)
  File "rpi-matrix-artnet.py", line 154, in datagramReceived
    self.showDisplay(display_size_x,display_size_y,frameBuffer,rgbframeLength)
  File "rpi-matrix-artnet.py", line 166, in showDisplay
    b = datastream[idx]
exceptions.IndexError: list index out of range`
